language: python
sudo: false
cache:
  directories:
  - "$HOME/.pip-cache/"
env:
  global:
  - PIP_WHEEL_DIR=$HOME/.cache/pip/wheels
  - PIP_FIND_LINKS=file://$HOME/.cache/pip/wheels
python:
- '3.7'
addons:
  apt:
    packages:
    - gdal-bin
    - libgdal-dev
install:
- pip wheel -r requirements.txt
- pip install .
script: pytest
deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: CgG+j81q8W540ITdU9EGETT5EL5khb3V7QJSfSmk6QzmsRRxPPzDUW1V672THeu+EZoBLA3/xql3vk0amIZ9vWXydkRvJhKpx+vRvmy5iHJFARf+cF5sjvKoM9LDDiF6Dlim++492kSEZi6mjsU9J18Zzrhm/kWYz+j2z0RvckJX0l6ziAGcqhyH8Ed+yLC9wnQGeKPR7gvBxUfVB6ibTuljGHd+ks1k2XsDQjPb3WknfkFfJ6hrw4L/MeN0+E9+zxXg9u/Bhhou6BsNFRyn58OH/06gugIsJCtR6oiUkOILuvzou44KpgDk017C71F6IdJNd066EVLyDV1sibwtF5bIcCYJOcBcJ+Pejf73rrJfX1vHIsOEfrY+/Sl+/MK/bTUOfKfgCfAq8UBx/1/j09l3f9spYQVESx3SFrcYBhDfGwo35eRWtXK8hKq/cBI/kS2LMTNRGnt0uk07l6QDr0PyHfqBba6ENv8gqIYD/un9Q/TyyKDG+ZahXMcvjw31PAL6SbNptYuiZRF9lTh3bSAjJs0HsqEyxFU0n5Jhh9lLP03gdd83FMvzbIXCB5P1ABcCxg5a3Sw5ipU2EKxU1jMO69oEAz65WtBxz5UC6dcqeK2DLOnbd2zEaKdm7uqT5xbOs9fytmq6UrpqGpUaUNJJ8itjIh+Qa/3CZPdYvy8=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: mrahnis/orangery
  skip_cleanup: true
