language: python
sudo: false
cache:
  directories:
  - "$HOME/.pip-cache/"
env:
  global:
  - PIP_WHEEL_DIR=$HOME/.cache/pip/wheels
  - PIP_FIND_LINKS=file://$HOME/.cache/pip/wheels
python:
- '3.6'
addons:
  apt:
    packages:
    - gdal-bin
    - libgdal-dev
install:
- pip wheel -r requirements.txt
- pip install .
script: pytest
deploy:
  provider: pypi
  user: mrahnis
  password:
    secure: JM75SNSNodJSHFnqgigkLISFWwV1UNnSASA6owwPs4YmSqnsmvKeJs6ot9SMBg2Xn1y5wEd7UK1w2pA4xWj05Fv5R4dzI2rfZ9Ievp1n4W0fadLZBHjTBYekEPEDBkS4r0JKQMHDKDxhydU4rb0r+6O7ieg1eXZRepJCoPPzLvnB+E30K5MPBJXNPIZrRwANRX9w0VIyVrmmUpxs+SD20cL8phMAUt8EFyKOgimbMkg6ncKb14TyVXDOfddWeLhIoc2TNHcWPPyhhjL7qtjd96VLICyyCuSV8/DwQDWa/G/clx67FQAfl0eeou8p93f9fE3bPn7xZUYhNLFEKhCwdgtA00CwqcytDd3uE1AotGxf4LcOr13aB4znFYSQ4ETAVlz+wYnufJEAC0JABR9KEp0Wo5i4nyFsMESHIBVJVqX5tmRzdT6gYvzhg4lzL1imY/rBBk0f2IIdwGsU1/Z5zYuuHgK6XzDV++7cof5pSBxmoY/iSEb+LnL8M8xphbb/mtbwZGUR2qQdIq+JiiJ5wRnsJy7MgsHWyIuOpB5fWbzLCj+BBK9WBU0CmGHW1IHwoYc218B0puPxvHrq4LV9NEMKWFjQxFbMe1fKG1N7l3kEjD1xPDwr//d6/1vqqK5Hetg4O2xQIe279SFrMXRMS04jwLwYc9IphO6tSkTN0rg=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: mrahnis/orangery
  skip_cleanup: true
