[project]
name = "orangery"
version = "0.1.0"
description = "Add a short description here"
authors = ["mrahnis <mrahnis@users.noreply.github.com>"]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]

[tasks]

[dependencies]
click = ">=8.1.7,<8.2"
shapely = ">=2.0.2,<2.1"
matplotlib = ">=3.8.2,<3.9"
pandas = ">=2.1.4,<2.2"
pip = ">=23.3.2,<23.4"
setuptools = ">=69.0.3,<69.1"
