package:
  name: orangery
  version: "0.4.0"

source:
  git_url: https://github.com/mrahnis/orangery.git
  git_rev: head

build:
  noarch: python
  number: 1
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - cutfill = orangery.cli.cutfill:cli
    - adjust = orangery.cli.adjust:cli
    - geodetic = orangery.cli.geodetic:cli

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - click
    - pandas
    - matplotlib
    - shapely
    - descartes
    - rasterio
    - fiona
    - networkx
    - opusxml
test:
  imports:
    - orangery
  commands:
    - cutfill --help

about:
  home: https://github.com/mrahnis/orangery
  license: BSD
  license_file: LICENSE.txt