{% set data = load_setup_py_data() %}
{% set version = data.get('version')  %}

package:
  name: orangery
  version: {{ version }}

source:
  git_url: https://github.com/mrahnis/orangery.git
  git_rev: HEAD

build:
  noarch: python
  number: 1
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - orangery = orangery.cli.orangery:cli

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy x.x
    - click
    - pandas
    - matplotlib
    - shapely 2.0.*
    - descartes
    - rasterio
    - fiona
    - networkx
    - opusxml
test:
  imports:
    - orangery
  commands:
    - orangery --help

about:
  home: https://github.com/mrahnis/orangery
  description: Python library to support analysis of topographic cross-sections
  license: BSD
  license_file: LICENSE.txt