{% set pyproject = load_file_data('pyproject.toml') %}
{% set version = pyproject.get('project').get('version') %}

package:
  name: orangery
  version: {{ version }}

source:
  git_url: https://github.com/mrahnis/orangery.git
  git_rev: HEAD

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - orangery = orangery.cli.orangery:cli

requirements:
  build:
    - python
    - setuptools
    - numpy
  run:
    {% for dependency in pyproject['project']['dependencies'] %}
    - {{ dependency.lower() }}
    {% endfor %}

test:
  imports:
    - orangery
  commands:
    - orangery --help

about:
  home: https://github.com/mrahnis/orangery
  description: Python library to support analysis of topographic cross-sections
  license: BSD
  license_file: LICENSE.txt
  
# https://github.com/conda/conda-build/issues/4807
# whatever_you_do_don't_load_setup_py_dataxxx!!!
